# Generated by Django 2.2.4 on 2019-11-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoDeDados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='tipoDaCarga',
            field=models.CharField(blank=True, choices=[('luminaria', 'luminaria'), ('ar condicionado', 'ar condicionado')], max_length=80),
        ),
    ]
